var uk_post_districts,uk_map;jQuery.getJSON("data/uk.json",function(b){uk_map=b;addMap()});jQuery.getJSON("data/uk_post_districs.json",function(b){$("#loading").hide();uk_post_districts=b;dataReady()});var current_rivalry=0,team1,team2,colorMin,colorMax,geojson,map,info,oms,color1,color2,colorInfo={cutpoints:[],colors:[]},stadiums={};
$(document).ready(function(){for(var b=$("#rivalryList"),a=0;a<rivalries.length;a++){var e=rivalries[a],d=$("<li/>");$("<a/>",{href:"#riv"+a,title:e.rivalry_info,text:e.name,"class":"dataLink"}).appendTo(d);d.appendTo(b)}var b=$("#teamList"),c;for(c in teamsData)"random"!=c&&(d=$("<li/>"),$("<a/>",{href:"#"+c,title:teamsData[c].name,text:teamsData[c].name,"class":"dataLink"}).appendTo(d),d.appendTo(b));$("a.dataLink").click(function(){$("#controlwrapper").animate({marginBottom:"-340px"},400);$("#maplegend").toggle();
$(".info").toggle();showData($(this).attr("href"))});$("#closeBtn").click(function(){$("#controlwrapper").animate({marginBottom:"-340px"},400);$("#maplegend").toggle();$(".info").toggle()});map=L.map("map",{minZoom:5,maxZoom:11,zoomControl:!1,attributionControl:!1}).fitBounds([[57.5,-8.3],[48.8,2.48]]);addMap();oms=new OverlappingMarkerSpiderfier(map,{keepSpiderfied:!0,alwaysSpiderfied:!0});oms.addListener("click",function(b){var b=teamsData[b.options["var"]].stadium,a=map.getMaxZoom();map.setView(b,
a)});map.on("zoomend",function(){"random"!=team2&&oms.spiderfyMarker(stadiums[team1])});for(c in teamsData)teamsData[c].stadium&&(b=L.icon({iconUrl:"img/markers/"+teamsData[c].crest,iconSize:[40,40],iconAnchor:[20,20]}),b=L.marker(teamsData[c].stadium,{title:teamsData[c].name,icon:b,"var":teamsData[c].variable}).addTo(map),stadiums[c]=b);info=L.control();info.onAdd=function(){this._div=L.DomUtil.create("div","info");this.update();return this._div};info.update=function(b){if(b){var a=b.post_4,c=twitterData[a].random,
b=[],f;for(f in teamsData)if("random"!=f&&0!=twitterData[a][f]){var d=0==twitterData[a][f]?0:Math.round(1E3*twitterData[a][f]/c);b.push([f,d])}b.sort(function(a,b){return b[1]-a[1]});var e=c=0,h=0,a="<h5>Twitter Fandom</h5><p>For postcode district: "+a+"</p>";if(0<b.length){var a=a+'<table><tr><th class="datacol">&nbsp;</th><th style="text-align: left;">Team</th></tr>',g;for(g in b){f=b[g][0];d=b[g][1];c++;a+='<tr><td class="datacol">';h==d?a+="="+e:(e=c,a+=e,h=d);a+="</td><td>";if(f==team1||f==team2)a+=
"<strong style='color:#08C'>";a+=teamsData[f].name;if(f==team1||f==team2)a+="</strong>";a+="</td></tr>"}a+="</table><br/>"}else a+="No data available for this region.";this._div.innerHTML="<small>"+a+"</small>"}else this._div.innerHTML="<h5>Twitter Fandom</h5><small>Hover over a postcode region.</small>"};info.addTo(map);$("#controlButton").click(function(){var a=$("#controlwrapper").css("marginBottom").replace("px","");$("#maplegend").toggle();$(".info").toggle();$("#controlwrapper").animate({marginBottom:0==
a?-340:0},400)});$("a.fancybox").fancybox({minWidth:400,maxWidth:800,maxHeight:600});c=document.location.hash;if(""==c||"#"==c)c="#riv0";prepareGUI(c)});function addMap(){map&&L.geoJson(uk_map,{style:function(){return{color:"#000",fillColor:"#cccccc",weight:0.5}}}).addTo(map)}
function prepareGUI(b){-1!=b.indexOf("#riv")?(current_rivalry=b.substr(4),team1=rivalries[current_rivalry].teams[0].variable,team2=rivalries[current_rivalry].teams[1].variable,color1=teamsData[team1].color,color2=teamsData[team2].color,$("#team2logo").show(),$("#team2name").show(),$("#team2logo").attr("src","img/crests/"+teamsData[team2].crest),$("#team2name").text(teamsData[team2].name)):(team1=teamsData[b.substr(1)].variable,team2="random",color1=teamsData[team1].color,color2="#aaaaaa",$("#team2logo").hide(),
$("#team2name").hide());$("#team1logo").attr("src","img/crests/"+teamsData[team1].crest);$("#team1name").text(teamsData[team1].name);for(var a in stadiums)a==team1||a==team2?(map.addLayer(stadiums[a]),oms.addMarker(stadiums[a])):(map.removeLayer(stadiums[a]),oms.removeMarker(stadiums[a]));"random"!=team2&&oms.spiderfyMarker(stadiums[team1])}function showData(b){prepareGUI(b);dataReady()}
function dataReady(){for(var b=[],a=0;a<uk_post_districts.features.length;a++){var e=uk_post_districts.features[a].properties.post_4,d=twitterData[e][team1],e=twitterData[e][team2];0==d||0==e||b.push(d/(d+e))}b.sort();colorMin=b[0];colorMax=b[b.length-1];colorInfo.cutpoints=[];colorInfo.cutpoints.push(b[Math.floor(0.25*b.length)]);colorInfo.cutpoints.push(b[Math.floor(0.5*b.length)]);colorInfo.cutpoints.push(b[Math.floor(0.75*b.length)]);colorInfo.colors=[];colorInfo.colors.push(color2);colorInfo.colors.push(normBlend(color1,
color2,0.33));colorInfo.colors.push(normBlend(color1,color2,0.67));colorInfo.colors.push(color1);b=$("#colorblocks");b.html("");if("random"!=team2){for(a=colorInfo.colors.length-1;0<=a;a--)$("<span/>").addClass("colorblock").css("background-color",colorInfo.colors[a]).appendTo(b);$("#colortext").hide()}else{for(a=colorInfo.colors.length-1;0<=a;a--)$("<span/>").addClass("colorblock").css("background-color",colorInfo.colors[a]).appendTo(b);$("#colortext").show()}geojson?geojson.setStyle(style):geojson=
L.geoJson(uk_post_districts,{style:style,onEachFeature:onEachFeature}).addTo(map)}function highlightFeature(b){b=b.target;b.setStyle({weight:2,color:"#ffffff",fillOpacity:0.4});!L.Browser.ie&&!L.Browser.opera&&b.bringToFront();info.update(b.feature.properties)}function resetHighlight(b){geojson.resetStyle(b.target);info.update()}function zoomToFeature(b){map.fitBounds(b.target.getBounds())}function onEachFeature(b,a){a.on({mouseover:highlightFeature,mouseout:resetHighlight,click:zoomToFeature})}
function style(b){var a;a=b.properties.post_4;b=twitterData[a][team1];a=twitterData[a][team2];0==b&&("random"==team2||0==a)?(b="#cccccc",a=0):(b=dataToColor(b/(b+a)),a=1);return{weight:0.2,opacity:1,color:"#666666",fillOpacity:a,fillColor:b}}function onEachFeature(b,a){a.on({mouseover:highlightFeature,mouseout:resetHighlight,click:zoomToFeature})}function dataToColor(b){for(var a=0;a<colorInfo.cutpoints.length&&b>colorInfo.cutpoints[a];)a++;return colorInfo.colors[a]};
