/*
 OverlappingMarkerSpiderfier
https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet
Copyright (c) 2011 - 2012 George MacKerron
Released under the MIT licence: http://opensource.org/licenses/mit-license
Note: The Leaflet maps API must be included *before* this code
*/
(function(){var o={}.hasOwnProperty,p=[].slice;null!=this.L&&(this.OverlappingMarkerSpiderfier=function(){function n(b,c){var a,e,g,f,d=this;this.map=b;null==c&&(c={});for(a in c)o.call(c,a)&&(e=c[a],this[a]=e);this.initMarkerArrays();this.listeners={};f=["click","zoomend"];e=0;for(g=f.length;e<g;e++)a=f[e],this.map.addEventListener(a,function(){return d.unspiderfy()})}var d,h;d=n.prototype;d.VERSION="0.2.5";h=2*Math.PI;d.alwaysSpiderfied=!1;d.keepSpiderfied=!1;d.nearbyDistance=20;d.circleSpiralSwitchover=
9;d.circleFootSeparation=25;d.circleStartAngle=h/12;d.spiralFootSeparation=28;d.spiralLengthStart=11;d.spiralLengthFactor=5;d.legWeight=1.5;d.legColors={usual:"#222",highlighted:"#f00"};d.initMarkerArrays=function(){this.markers=[];return this.markerListeners=[]};d.addMarker=function(b){var c,a=this;if(null!=b._oms)return this;b._oms=!0;c=function(){return a.spiderListener(b)};b.addEventListener("click",c);this.markerListeners.push(c);this.markers.push(b);return this};d.getMarkers=function(){return this.markers.slice(0)};
d.removeMarker=function(b){var c,a;null!=b._omsData&&this.unspiderfy();c=this.arrIndexOf(this.markers,b);if(0>c)return this;a=this.markerListeners.splice(c,1)[0];b.removeEventListener("click",a);delete b._oms;this.markers.splice(c,1);return this};d.clearMarkers=function(){var b,c,a,e,g;this.unspiderfy();g=this.markers;b=a=0;for(e=g.length;a<e;b=++a)c=g[b],b=this.markerListeners[b],c.removeEventListener("click",b),delete c._oms;this.initMarkerArrays();return this};d.addListener=function(b,c){var a,
e;(null!=(e=(a=this.listeners)[b])?e:a[b]=[]).push(c);return this};d.removeListener=function(b,c){var a;a=this.arrIndexOf(this.listeners[b],c);0>a||this.listeners[b].splice(a,1);return this};d.clearListeners=function(b){this.listeners[b]=[];return this};d.trigger=function(){var b,c,a,e,g,f;c=arguments[0];b=2<=arguments.length?p.call(arguments,1):[];c=null!=(a=this.listeners[c])?a:[];f=[];e=0;for(g=c.length;e<g;e++)a=c[e],f.push(a.apply(null,b));return f};d.generatePtsCircle=function(b,c){var a,e,
g,f,d;g=this.circleFootSeparation*(2+b)/h;e=h/b;d=[];for(a=f=0;0<=b?f<b:f>b;a=0<=b?++f:--f)a=this.circleStartAngle+a*e,d.push(new L.Point(c.x+g*Math.cos(a),c.y+g*Math.sin(a)));return d};d.generatePtsSpiral=function(b,c){var a,e,g,f,d;g=this.spiralLengthStart;a=0;d=[];for(e=f=0;0<=b?f<b:f>b;e=0<=b?++f:--f)a+=this.spiralFootSeparation/g+5.0E-4*e,e=new L.Point(c.x+g*Math.cos(a),c.y+g*Math.sin(a)),g+=h*this.spiralLengthFactor/a,d.push(e);return d};d.spiderListener=function(b){var c;c=null!=b._omsData;
(!c||!this.keepSpiderfied)&&this.unspiderfy();return c?this.trigger("click",b):this.spiderfyMarker(b,!0)};d.spiderfyMarker=function(b,c){var a,e,g,f,d,i,j,k,l;f=[];d=[];i=this.nearbyDistance*this.nearbyDistance;g=this.map.latLngToLayerPoint(b.getLatLng());l=this.markers;j=0;for(k=l.length;j<k;j++)a=l[j],e=this.map.latLngToLayerPoint(a.getLatLng()),this.ptDistanceSq(e,g)<i?f.push({marker:a,markerPt:e}):d.push(a);return 1===f.length?c&&this.trigger("click",b):this.spiderfy(f,d)};d.makeHighlightListeners=
function(b){var c=this;return{highlight:function(){return b._omsData.leg.setStyle({color:c.legColors.highlighted})},unhighlight:function(){return b._omsData.leg.setStyle({color:c.legColors.usual})}}};d.spiderfy=function(b,c){var a,e,d,f,m,i,j,k,l,h;this.spiderfying=!0;h=b.length;a=this.ptAverage(function(){var a,c,e;e=[];a=0;for(c=b.length;a<c;a++)j=b[a],e.push(j.markerPt);return e}());f=h>=this.circleSpiralSwitchover?this.generatePtsSpiral(h,a).reverse():this.generatePtsCircle(h,a);a=function(){var a,
c,h,j=this;h=[];a=0;for(c=f.length;a<c;a++)d=f[a],e=this.map.layerPointToLatLng(d),l=this.minExtract(b,function(a){return j.ptDistanceSq(a.markerPt,d)}),i=l.marker,m=new L.Polyline([i.getLatLng(),e],{color:this.legColors.usual,weight:this.legWeight,clickable:!1}),this.map.addLayer(m),i._omsData={usualPosition:i.getLatLng(),leg:m},this.legColors.highlighted!==this.legColors.usual&&(k=this.makeHighlightListeners(i),i._omsData.highlightListeners=k,i.addEventListener("mouseover",k.highlight),i.addEventListener("mouseout",
k.unhighlight)),i.setLatLng(e),i.setZIndexOffset(1E6),h.push(i);return h}.call(this);delete this.spiderfying;this.spiderfied=!0;return this.trigger("spiderfy",a,c)};d.unspiderfy=function(b){var c,a,e,d,f,h,i;null==b&&(b=null);if(null==this.spiderfied)return this;this.unspiderfying=!0;d=[];e=[];i=this.markers;f=0;for(h=i.length;f<h;f++)c=i[f],null!=c._omsData?(this.map.removeLayer(c._omsData.leg),c!==b&&c.setLatLng(c._omsData.usualPosition),c.setZIndexOffset(0),a=c._omsData.highlightListeners,null!=
a&&(c.removeEventListener("mouseover",a.highlight),c.removeEventListener("mouseout",a.unhighlight)),delete c._omsData,d.push(c)):e.push(c);delete this.unspiderfying;delete this.spiderfied;this.trigger("unspiderfy",d,e);return this};d.ptDistanceSq=function(b,c){var a,e;a=b.x-c.x;e=b.y-c.y;return a*a+e*e};d.ptAverage=function(b){var c,a,e,d,f;d=a=e=0;for(f=b.length;d<f;d++)c=b[d],a+=c.x,e+=c.y;b=b.length;return new L.Point(a/b,e/b)};d.minExtract=function(b,c){var a,d,g,f,h,i;g=h=0;for(i=b.length;h<
i;g=++h)if(f=b[g],f=c(f),!("undefined"!==typeof a&&null!==a)||f<d)d=f,a=g;return b.splice(a,1)[0]};d.arrIndexOf=function(b,c){var a,d,g,f;if(null!=b.indexOf)return b.indexOf(c);a=g=0;for(f=b.length;g<f;a=++g)if(d=b[a],d===c)return a;return-1};return n}())}).call(this);
